spring.application.name=AssetManagement
spring.datasource.url=jdbc:postgresql://localhost:5432/assetmanagement
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# JWT Configuration
app.jwt.secret=AssetManagementSuperSecretJwtKeyForAuthentication20261234567890
app.jwt.expiration-ms=86400000
